### ISSUE TITLE
Create a "last 10 articles" component at the end of post layout

### ISSUE THREAD

**Issue by Slashgear** [open-blog-initiative/open-blog.dev#19]
In order to define inner linking in the blog, it could be great to have a component that display last articles by publication date and local.

Example:
<img width="1083" alt="Capture d’écran 2019-04-02 à 19 44 39" src="https://user-images.githubusercontent.com/6263857/55424115-d25c9080-557f-11e9-97d4-b077e328e7b6.png">

**Comment by agory** [comment]
Work In Progress 😄
